apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-service
  name: hello-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    role: web
